### PR TITLE
Migrate to the new cy.intercept

### PR DESCRIPTION
**Pull request by mhssmnn**

### CODE REVIEW

**Comment by Nanciee** [comment]
Can't tell you how much I appreciate this! I've been trying to find the time to add in tests for a long time! Is this still wip?

**Comment by mhssmnn** [comment]
I appreciate you writing this plugin! It's probably good to go. I split this into two PRs so that you can either just merge in the tests or the tests and the cy.intercept (which would be a breaking change and require Cypress 6.0). 

I've also only written some very basic tests just to help ensure migrating to cy.intercept didn't break anything.

**Comment by tondi** [comment]
Would be nice to have this :) We probably also want to update the `How does the recording and stubbing work?` section
in `README.md` as it mentions `cy.server()` as underlying mechanism - https://github.com/Nanciee/cypress-autorecord#how-does-the-recording-and-stubbing-work

**Comment by OmriSama** [comment]
@Nanciee is this ready for merge? I'm interested in using this

**Pull request merged**
